tasks:
  - init: pip install -r requirements.txt
    commad: mkdir install && cd install
    commad: git clone https://github.com/openmc-dev/openmc.git && cd openmc
    commad: pip install . && cmake . && cd ../
